### ISSUE TITLE
BUG: Failed to load script "res://scenes/autoload/mixer_control.gd" with error "Parse error".

### ISSUE THREAD

**Issue by sphis-Sinco** [what-is-a-git/FunkinGodot#3]
I get this little error when I open the Godot project (rewrite branch)

![image](https://github.com/user-attachments/assets/11bd5a73-98cd-433f-a00a-a2acaf3643e7)

**Comment by what-is-a-git** [comment]
if it works now then it's probably more a godot / migrating to newer commits thing, so uh, :3c

**Comment by sphis-Sinco** [comment]
ah ok
